/**
 * Generates `src/blobs-builtin.c`, the data tinyimg ships inside the module.
 *
 * ```sh
 * bun scripts/blobs-builtin.ts           # regenerate
 * bun scripts/blobs-builtin.ts --check   # verify the committed file matches its inputs
 * ```
 *
 * Every input is committed, so this runs and verifies with no network. The ICC profiles are
 * rebuilt from `scripts/icc.ts`, which synthesizes them from primaries and tone curves; the face
 * and the cascades are the same committed artifacts the tests read, and the face is re-subset from
 * `blobs/fonts/DejaVuSans.ttf` when that download is present so the two cannot drift.
 *
 * Third-party notices for the face and the cascades are in `LICENSES/`.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { SUBSET_ACCENTS, SUBSET_ASCII, subsetFont } from './fonts.ts';
import { SPACES, buildProfile } from './icc.ts';

const ROOT = join(dirname(new URL(import.meta.url).pathname), '..');
const OUT = join(ROOT, 'src', 'blobs-builtin.c');
const DERIVED = join(ROOT, 'tests', 'fixtures', 'derived');

/** One entry of the generated table. */
interface Builtin {
	kind: 'FONT' | 'ICC' | 'CASCADE';
	id: string;
	symbol: string;
	bytes: Buffer;
	note: string;
}

/**
 * The default face.
 *
 * DejaVu Sans cut to ASCII plus eight accented codepoints, which is 20.9 KB against the 757 KB
 * face. `subsetFont` is deterministic, so subsetting the download and reading the committed
 * fixture give the same bytes; when both are available they are compared rather than one being
 * trusted.
 */
function font(): Builtin {
	const committed = join(DERIVED, 'fonts', 'dejavu-latin.ttf');
	const download = join(ROOT, 'blobs', 'fonts', 'DejaVuSans.ttf');

	let bytes: Buffer | undefined;

	if (existsSync(download)) {
		bytes = subsetFont(readFileSync(download), [...SUBSET_ASCII, ...SUBSET_ACCENTS], 4).bytes;
	}

	if (existsSync(committed)) {
		const have = readFileSync(committed);

		if (bytes && !bytes.equals(have)) {
			throw new Error(
				`${committed} and a fresh subset of ${download} differ; run \`bun run fixtures\``
			);
		}

		bytes = have;
	}

	if (!bytes) {
		throw new Error(`neither ${committed} nor ${download} is present`);
	}

	return {
		kind: 'FONT',
		id: 'sans',
		symbol: 'builtin_font_sans',
		bytes,
		note: 'DejaVu Sans, ASCII plus eight accents, from scripts/fonts.ts'
	};
}

/** The four profiles, rebuilt from their primaries rather than read off disk. */
function icc(): Builtin[] {
	return SPACES.map((space) => ({
		kind: 'ICC' as const,
		id: space.id,
		symbol: `builtin_icc_${space.id.replace(/-/g, '_')}`,
		bytes: buildProfile(space),
		note: `${space.name}, from scripts/icc.ts`
	}));
}

/** The two packed LBP cascades, which are committed because the XML they came from is not. */
function cascades(): Builtin[] {
	return ['lbp-frontalface', 'lbp-profileface'].map((id) => {
		const path = join(DERIVED, 'cascades', `${id}.bin`);

		if (!existsSync(path)) throw new Error(`${path} is missing; run \`bun run fixtures\``);

		return {
			kind: 'CASCADE' as const,
			id,
			symbol: `builtin_cascade_${id.replace(/-/g, '_')}`,
			bytes: readFileSync(path),
			note: `OpenCV ${id}, packed by scripts/cascade.ts`
		};
	});
}

function array(entry: Builtin): string {
	const values: string[] = [];

	for (const byte of entry.bytes) values.push(String(byte));

	return (
		`// ${entry.note}\n` +
		`static const uint8_t ${entry.symbol}[${entry.bytes.length}] = {${values.join(',')}};`
	);
}

function generate(): string {
	const entries = [font(), ...icc(), ...cascades()];
	const total = entries.reduce((sum, entry) => sum + entry.bytes.length, 0);

	const rows = entries
		.map(
			(entry) =>
				`    {TINYIMG_BLOB_${entry.kind}, "${entry.id}", ${entry.symbol},` +
				` sizeof(${entry.symbol})},`
		)
		.join('\n');

	return `/*
 * Generated by scripts/blobs-builtin.ts. Do not hand edit.
 *
 * ${entries.length} blobs, ${total.toLocaleString()} bytes. Third-party notices are in LICENSES/.
 */
#include "tinyimg/memory.h"

${entries.map(array).join('\n\n')}

const TinyBlobBuiltin tiny_blob_builtins[] = {
${rows}
};

const uint32_t tiny_blob_builtin_count = ${entries.length}u;
`;
}

/**
 * Runs the output through clang-format.
 *
 * The file sits under `src/`, so `format.sh` formats it and `format:check` would fail the moment
 * anyone ran that. Formatting here keeps the two in agreement by construction.
 */
function formatted(text: string): string {
	return execFileSync('clang-format', [`--assume-filename=${OUT}`], {
		input: text,
		encoding: 'utf8',
		maxBuffer: 256 * 1024 * 1024
	});
}

const wanted = formatted(generate());

if (process.argv.includes('--check')) {
	const have = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';

	if (have !== wanted) {
		console.error(`${OUT} does not match its inputs`);
		process.exit(1);
	}

	console.log('blobs-builtin.c matches its inputs');
} else {
	writeFileSync(OUT, wanted);
	console.log(`wrote ${OUT}, ${wanted.length.toLocaleString()} bytes`);
}
