import { describe, expect, it } from 'vitest';
import bytes from '../../bin/tinyimg.wasm?bin';

/**
 * The same facts as the workers lane, checked where compiling from bytes is allowed.
 *
 * Both lanes exist because they fail differently: node accepts bytes and workerd does not, so a
 * loader that only ever ran here would pass every test and break on deploy.
 */
describe('the wasm module under node', () => {
	const module = new WebAssembly.Module(bytes);
	const instance = new WebAssembly.Instance(module, {});
	const exports = instance.exports as {
		tiny_version(): number;
		tiny_abi_version(): number;
		tiny_features(): number;
		tiny_error_name(code: number): number;
		memory: WebAssembly.Memory;
	};

	it('reports the version and abi the header declares', () => {
		expect(exports.tiny_version()).toBe(1 << 16);
		expect(exports.tiny_abi_version()).toBe(1);
	});

	it('imports nothing', () => {
		expect(WebAssembly.Module.imports(module)).toHaveLength(0);
	});

	it('exports memory, and only the documented surface', () => {
		expect(Object.keys(instance.exports).sort()).toEqual([
			'memory',
			'tiny_abi_version',
			'tiny_alloc',
			'tiny_arena_reset',
			'tiny_blob_free',
			'tiny_blob_free_all',
			'tiny_blob_load',
			'tiny_cascade_check',
			'tiny_cmyk_to_rgb',
			'tiny_detect_opts',
			'tiny_detect_opts_sizeof',
			'tiny_display_blend',
			'tiny_display_bounds',
			'tiny_display_covered',
			'tiny_display_culled',
			'tiny_display_ellipse',
			'tiny_display_init',
			'tiny_display_line',
			'tiny_display_polygon',
			'tiny_display_rect',
			'tiny_display_render',
			'tiny_display_restore',
			'tiny_display_rotate',
			'tiny_display_round_rect',
			'tiny_display_save',
			'tiny_display_scale',
			'tiny_display_set_transform',
			'tiny_display_sizeof',
			'tiny_display_translate',
			'tiny_encode_cost',
			'tiny_error_name',
			'tiny_face_box_sizeof',
			'tiny_features',
			'tiny_font_free',
			'tiny_font_has_glyph',
			'tiny_font_load',
			'tiny_font_metrics',
			'tiny_font_metrics_sizeof',
			'tiny_font_sizeof',
			'tiny_free',
			'tiny_gradient_cmyk',
			'tiny_gradient_hsl',
			'tiny_gradient_hsv',
			'tiny_gradient_rgb',
			'tiny_gradient_rgba',
			'tiny_grayscale_to_rgb',
			'tiny_heap_bootstrap',
			'tiny_hsl_to_rgb',
			'tiny_hsv_to_rgb',
			'tiny_icc_convert_image',
			'tiny_icc_matrix_between',
			'tiny_icc_parse',
			'tiny_icc_srgb',
			'tiny_icc_to_srgb',
			'tiny_image_apply_lut',
			'tiny_image_apply_luts',
			'tiny_image_apply_matrix',
			'tiny_image_apply_sepia',
			'tiny_image_arc',
			'tiny_image_auto_brightness',
			'tiny_image_auto_color',
			'tiny_image_auto_contrast',
			'tiny_image_auto_gamma',
			'tiny_image_auto_levels',
			'tiny_image_average_color',
			'tiny_image_barrel',
			'tiny_image_blackwhite',
			'tiny_image_blur',
			'tiny_image_blur_faces',
			'tiny_image_blur_region',
			'tiny_image_border',
			'tiny_image_brightness',
			'tiny_image_channel_gain',
			'tiny_image_channel_mixer',
			'tiny_image_chromatic_aberration',
			'tiny_image_clarity',
			'tiny_image_color_balance',
			'tiny_image_color_overlay',
			'tiny_image_color_overlay_rect',
			'tiny_image_colorblind_assist',
			'tiny_image_colorblind_simulate',
			'tiny_image_colorize',
			'tiny_image_composite',
			'tiny_image_contrast',
			'tiny_image_convert_channels',
			'tiny_image_corner_radius',
			'tiny_image_create',
			'tiny_image_crop',
			'tiny_image_crop_circle',
			'tiny_image_crop_ellipse',
			'tiny_image_crop_polygon',
			'tiny_image_curves',
			'tiny_image_darken',
			'tiny_image_decode',
			'tiny_image_dehaze',
			'tiny_image_despeckle',
			'tiny_image_destroy',
			'tiny_image_detect_faces',
			'tiny_image_detect_faces_ex',
			'tiny_image_dilate',
			'tiny_image_dither',
			'tiny_image_dominant_color',
			'tiny_image_draw_circle',
			'tiny_image_draw_ellipse',
			'tiny_image_draw_image',
			'tiny_image_draw_image_ex',
			'tiny_image_draw_line',
			'tiny_image_draw_text',
			'tiny_image_draw_text_box',
			'tiny_image_drop_shadow',
			'tiny_image_duotone',
			'tiny_image_emboss',
			'tiny_image_encode',
			'tiny_image_erode',
			'tiny_image_expand',
			'tiny_image_exposure',
			'tiny_image_fill_circle',
			'tiny_image_fill_ellipse',
			'tiny_image_fill_light',
			'tiny_image_fill_polygon',
			'tiny_image_fill_polygon_with',
			'tiny_image_fill_rectangle',
			'tiny_image_fill_rounded_rectangle',
			'tiny_image_film_grain',
			'tiny_image_fit',
			'tiny_image_fit_with_gravity',
			'tiny_image_flip_horizontal',
			'tiny_image_flip_vertical',
			'tiny_image_focus',
			'tiny_image_gamma_correction',
			'tiny_image_gaussian_blur',
			'tiny_image_get_exif',
			'tiny_image_get_metadata',
			'tiny_image_get_metadata_count',
			'tiny_image_getchannels',
			'tiny_image_getdata',
			'tiny_image_getformat',
			'tiny_image_getheight',
			'tiny_image_getsize',
			'tiny_image_getwidth',
			'tiny_image_glow',
			'tiny_image_gradient_fade',
			'tiny_image_gradient_linear',
			'tiny_image_gradient_radial',
			'tiny_image_halftone',
			'tiny_image_has_exif',
			'tiny_image_has_metadata',
			'tiny_image_histogram',
			'tiny_image_hline',
			'tiny_image_hue',
			'tiny_image_improve',
			'tiny_image_info_sizeof',
			'tiny_image_invert',
			'tiny_image_levels',
			'tiny_image_levels_channel',
			'tiny_image_lighten',
			'tiny_image_load',
			'tiny_image_load_region',
			'tiny_image_load_scaled',
			'tiny_image_morphology_close',
			'tiny_image_morphology_open',
			'tiny_image_motion_blur',
			'tiny_image_negate',
			'tiny_image_noise',
			'tiny_image_opacity',
			'tiny_image_outline',
			'tiny_image_palette',
			'tiny_image_perspective',
			'tiny_image_phash',
			'tiny_image_pixelate',
			'tiny_image_pixelate_faces',
			'tiny_image_pixelate_region',
			'tiny_image_polar',
			'tiny_image_polygon',
			'tiny_image_posterize',
			'tiny_image_premultiply',
			'tiny_image_preset',
			'tiny_image_probe',
			'tiny_image_radial_blur',
			'tiny_image_rectangle',
			'tiny_image_remove_background',
			'tiny_image_remove_metadata',
			'tiny_image_replace_color',
			'tiny_image_resize',
			'tiny_image_rotate',
			'tiny_image_rotate_180',
			'tiny_image_rotate_270',
			'tiny_image_rotate_90',
			'tiny_image_saturation',
			'tiny_image_scanlines',
			'tiny_image_set_exif',
			'tiny_image_set_metadata',
			'tiny_image_shadows_highlights',
			'tiny_image_sharpen',
			'tiny_image_shear',
			'tiny_image_sizeof',
			'tiny_image_sobel',
			'tiny_image_solarize',
			'tiny_image_split_tone',
			'tiny_image_strip_exif',
			'tiny_image_swirl',
			'tiny_image_temperature',
			'tiny_image_threshold',
			'tiny_image_tilt_shift',
			'tiny_image_tint',
			'tiny_image_trim',
			'tiny_image_unpremultiply',
			'tiny_image_unsharp_mask',
			'tiny_image_vibrance',
			'tiny_image_vignette',
			'tiny_image_vline',
			'tiny_image_white_balance',
			'tiny_image_zoom',
			'tiny_image_zoom_blur',
			'tiny_init',
			'tiny_interpolate_hsl',
			'tiny_interpolate_hsv',
			'tiny_interpolate_rgb',
			'tiny_multigradient_cmyk',
			'tiny_multigradient_cmyk_sized',
			'tiny_multigradient_hsl',
			'tiny_multigradient_hsl_sized',
			'tiny_multigradient_hsv',
			'tiny_multigradient_hsv_sized',
			'tiny_multigradient_rgb',
			'tiny_multigradient_rgb_sized',
			'tiny_multigradient_rgba',
			'tiny_multigradient_rgba_sized',
			'tiny_phash_distance',
			'tiny_plan_background',
			'tiny_plan_blur',
			'tiny_plan_brightness',
			'tiny_plan_contrast',
			'tiny_plan_cost',
			'tiny_plan_count',
			'tiny_plan_crop',
			'tiny_plan_curve',
			'tiny_plan_effect',
			'tiny_plan_effect_rect',
			'tiny_plan_encode',
			'tiny_plan_field',
			'tiny_plan_fit',
			'tiny_plan_fit_with',
			'tiny_plan_flip_horizontal',
			'tiny_plan_flip_vertical',
			'tiny_plan_gamma',
			'tiny_plan_gaussian_blur',
			'tiny_plan_grayscale',
			'tiny_plan_hue',
			'tiny_plan_init',
			'tiny_plan_init_image',
			'tiny_plan_invert',
			'tiny_plan_matrix',
			'tiny_plan_resize',
			'tiny_plan_resize_with',
			'tiny_plan_resolution_sizeof',
			'tiny_plan_resolve',
			'tiny_plan_rotate',
			'tiny_plan_run',
			'tiny_plan_saturation',
			'tiny_plan_set_effort',
			'tiny_plan_set_fusion',
			'tiny_plan_sizeof',
			'tiny_realloc',
			'tiny_rgb_to_cmyk',
			'tiny_rgb_to_grayscale',
			'tiny_rgb_to_hsl',
			'tiny_rgb_to_hsv',
			'tiny_text_measure',
			'tiny_text_measure_wrapped',
			'tiny_text_metrics_sizeof',
			'tiny_text_style',
			'tiny_text_style_sizeof',
			'tiny_version',
			'tiny_work_read',
			'tiny_work_reset',
			'tiny_writer_data',
			'tiny_writer_detach',
			'tiny_writer_free',
			'tiny_writer_init',
			'tiny_writer_size',
			'tiny_writer_sizeof'
		]);
	});

	it('returns a pointer into its own memory for an error name', () => {
		const pointer = exports.tiny_error_name(-4);
		expect(pointer).toBeGreaterThan(0);
		expect(pointer).toBeLessThan(exports.memory.buffer.byteLength);

		const view = new Uint8Array(exports.memory.buffer, pointer);
		const end = view.indexOf(0);
		expect(new TextDecoder().decode(view.subarray(0, end))).toBe('out of memory');
	});

	it('names an unrecognized code rather than reading past the table', () => {
		const pointer = exports.tiny_error_name(-9999);
		const view = new Uint8Array(exports.memory.buffer, pointer);
		const end = view.indexOf(0);
		expect(new TextDecoder().decode(view.subarray(0, end))).toBe('unknown');
	});

	it('reports every codec this build was compiled with', () => {
		const features = exports.tiny_features();
		const names = ['SIMD', 'PNG', 'JPEG', 'BMP', 'GIF', 'TIFF', 'WEBP', 'AVIF'];
		for (const [index, name] of names.entries()) {
			expect(features & (1 << index), `${name} should be compiled in`).toBeTruthy();
		}
	});
});
